import {
  FaCloud,
  FaFire,
  FaChair,
  FaShower,
  FaTemperatureLow,
  FaBed,
  FaTable,
  FaSolarPanel,
  FaUtensils,
  FaLightbulb,
  FaParking,
  FaWifi,
  FaSwimmingPool,
  FaBiking,
  FaSpa,
  FaTv,
  FaCampground,
  FaBolt,
  FaCar,
  FaWater,
  FaMountain,
  FaDog,
  FaThermometerHalf,
} from "react-icons/fa";

export const amenities = [
  { name: "Unlimited Cloud Storage", icon: FaCloud, selected: false },
  { name: "Self-Lighting Fire pit", icon: FaFire, selected: false },
  { name: "Outdoor Furniture (Tree stumps)", icon: FaChair, selected: false },
  { name: "Hot Shower (Sun required)", icon: FaShower, selected: false },
  {
    name: "Natural Heating (Bring a coat)",
    icon: FaTemperatureLow,
    selected: false,
  },
  { name: "Bed Linens", icon: FaBed, selected: false },
  { name: "Picnic Table", icon: FaTable, selected: false },
  { name: "Solar Power", icon: FaSolarPanel, selected: false },
  { name: "Cooking Utensils", icon: FaUtensils, selected: false },
  { name: "Lanterns", icon: FaLightbulb, selected: false },
  { name: "VIP Parking", icon: FaParking, selected: false },

  // Additional amenities with their respective icons
  { name: "WiFi", icon: FaWifi, selected: false },
  { name: "Swimming Pool", icon: FaSwimmingPool, selected: false },
  { name: "Bicycles for Rent", icon: FaBiking, selected: false },
  { name: "Spa", icon: FaSpa, selected: false },
  { name: "Television", icon: FaTv, selected: false },
  { name: "Campground", icon: FaCampground, selected: false },
  { name: "Electric Charging Station", icon: FaBolt, selected: false },
  { name: "Car Rental", icon: FaCar, selected: false },
  { name: "Freshwater Stream", icon: FaWater, selected: false },
  { name: "Mountain View", icon: FaMountain, selected: false },
  { name: "Pet-Friendly", icon: FaDog, selected: false },
  { name: "Heating", icon: FaThermometerHalf, selected: false },
];
